
name: prod-api

services:

  db:
    image: postgres:18
    hostname: db
    environment:
      POSTGRES_USER: ${DB_USER:-store}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-devpass}
      POSTGRES_DB: ${DB_NAME:-store}

  account:
    image: cheqr/account:latest
    hostname: account
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_DB: ${DB_NAME:-store}
      DATABASE_USERNAME: ${DB_USER:-store}
      DATABASE_PASSWORD: ${DB_PASSWORD:-devpass}
    deploy:
      replicas: 1
    depends_on:
      - db

  # auth:
  #   image: cheqr/auth:latest
  #   hostname: auth
  #   deploy:
  #     replicas: 1
  #   environment:
  #     JWT_SECRET_KEY: ${JWT_SECRET_KEY:-jYCiN0YPiaBP53bGJi/kjfw79HW7xnBu9UPoD/QFFAE=}
  #     JWT_HTTP_ONLY: ${JWT_HTTP_ONLY:-true}
  #   depends_on:
  #     - account

  # gateway:
  #   image: cheqr/gateway:latest
  #   hostname: gateway
  #   environment:
  #     CORS_ALLOWED_CREDENTIALS: ${CORS_ALLOWED_CREDENTIALS:-true}
  #     CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS:-*}
  #   ports:
  #     - 8080:8080

  # exchange:
  #   image: cheqr/exchange:latest
  #   hostname: exchange
  #   environment:
  #     PORT: 8000
  #   deploy:
  #     replicas: 1

  # product:
  #   image: cheqr/product:latest
  #   hostname: product
  #   environment:
  #     DATABASE_HOST: db
  #     DATABASE_PORT: 5432
  #     DATABASE_DB: ${DB_NAME:-store}
  #     DATABASE_USERNAME: ${DB_USER:-store}
  #     DATABASE_PASSWORD: ${DB_PASSWORD:-devpass}
  #   deploy:
  #     replicas: 1
  #   depends_on:
  #     - db

  # order:
  #   image: cheqr/order:latest
  #   hostname: order
  #   environment:
  #     DATABASE_HOST: db
  #     DATABASE_PORT: 5432
  #     DATABASE_DB: ${DB_NAME:-store}
  #     DATABASE_USERNAME: ${DB_USER:-store}
  #     DATABASE_PASSWORD: ${DB_PASSWORD:-devpass}
  #     PRODUCT_SERVICE_URL: http://product:8080
  #     EXCHANGE_SERVICE_URL: http://exchange:8000
  #   deploy:
  #     replicas: 1
  #   depends_on:
  #     - db
  #     - product
  #     - exchange
